name: Build
on: [pull_request, push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install NDK
        run: echo "y" | sudo ${ANDROID_HOME}/tools/bin/sdkmanager --install "ndk;21.0.6113669"
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Build all subproject aar files
        run: cd SmartCredentials_aOS && ./gradlew assembleRelease
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
            name: authentication
            path: SmartCredentials_aOS/authentication/build/outputs/aar/authentication-release-6.2.1.aar
