name: Build
on: [pull_request, push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install NDK
        run: echo "y" | sudo sdkmanager --install "ndk;21.0.6113669"
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Build the app
        run: env && ls && cd SmartCredentials_aOS && ./gradlew assembleDebug 
