name: Build Samples
on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: lint
        run: cd samples/authentication && bash ./gradlew lint 
      - name: Build authentication apk
        run: cd samples/authentication && bash ./gradlew assemble
