name: Build Samples
on: [pull_request, push]
branches: main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install NDK
        run: echo "y" | sudo ${ANDROID_HOME}/tools/bin/sdkmanager --install "ndk;21.0.6113669"
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: lint
        run: cd samples/authentication && ./gradlew lint 
      - name: Build authentication apk
        run: cd samples/authentication && ./gradlew assemble
