name: Build Samples
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: lint
        run: cd samples/authentication && ./gradlew lint 
      - name: Build authentication apk
        run: cd samples/authentication && ./gradlew assemble
